<a href="https://colab.research.google.com/github/Deepshika-Mekala/deepshikamekala.github.io/blob/main/Deepshika_Mekala_ass4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 4: Neural Networks (30 marks)
### Due date: March 31 at 11:59pm
*Author: Deepshika Mekala

For this assignment, you will be practicing using scikit-learn and TensorFlow to implement basic neural networks (MLP). You can use the given dataset below, or you can use the dataset you have selected for your project.

**Note: If you use the dataset from your project - this assignment is meant to be completed individually. You may work with your group members to complete this assignment, but the work you submit must be your own. Submitting identical assignments is a form of academic misconduct**

In [ ]:
import numpy as np
import pandas as pd

## Part 1: Load your dataset (1 mark)

As stated above, you can use the dataset from your project. If you want to practice neural networks with a different dataset, you can use the energy dataset from Yellowbrick (https://www.scikit-yb.org/en/latest/api/datasets/energy.html)

In [ ]:
from yellowbrick.datasets import load_energy

X, y = load_energy()
print('X.shape={}, type(X)={}'.format(X.shape, type(X)))
print('y.shape={}, type(y)={}'.format(y.shape, type(y)))

X.shape=(768, 8), type(X)=<class 'pandas.core.frame.DataFrame'>
y.shape=(768,), type(y)=<class 'pandas.core.series.Series'>

## Part 2: Process your dataset (5 marks)

In [ ]:
# Check if there are any missing values - if yes, decide how to fill them
data = pd.DataFrame(X)
data.info()
data.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   relative compactness       768 non-null    float64
 1   surface area               768 non-null    float64
 2   wall area                  768 non-null    float64
 3   roof area                  768 non-null    float64
 4   overall height             768 non-null    float64
 5   orientation                768 non-null    int64
 6   glazing area               768 non-null    float64
 7   glazing area distribution  768 non-null    int64
dtypes: float64(6), int64(2)
memory usage: 48.1 KB

relative compactness         0
surface area                 0
wall area                    0
roof area                    0
overall height               0
orientation                  0
glazing area                 0
glazing area distribution    0
dtype: int64

In [ ]:
# Check the range of each feature - do you need to scale your data?
data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
relative compactness,768.0,0.764167,0.105777,0.62,0.6825,0.75,0.830,0.98
surface area,768.0,671.708333,88.086116,514.50,606.3750,673.75,741.125,808.50
wall area,768.0,318.500000,43.626481,245.00,294.0000,318.50,343.000,416.50
roof area,768.0,176.604167,45.165950,110.25,140.8750,183.75,220.500,220.50
overall height,768.0,5.250000,1.751140,3.50,3.5000,5.25,7.000,7.00
orientation,768.0,3.500000,1.118763,2.00,2.7500,3.50,4.250,5.00
glazing area,768.0,0.234375,0.133221,0.00,0.1000,0.25,0.400,0.40
glazing area distribution,768.0,2.812500,1.550960,0.00,1.7500,3.00,4.000,5.00

In [ ]:
data.nunique()

relative compactness         12
surface area                 12
wall area                     7
roof area                     4
overall height                2
orientation                   4
glazing area                  4
glazing area distribution     6
dtype: int64

In [ ]:
# Split your data into training and testing datasets (select random_state=0 and use default test_size)
from sklearn.model_selection import train_test_split as tts

X_train, X_test, y_train, y_test = tts(X, y, random_state=0)

In [ ]:
# Implement scaling and/or encoding here if needed (2 marks for preprocessing properly or justifying why it isn't needed)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

column = ColumnTransformer(
    [("scaling", StandardScaler(), ['relative compactness', 'surface area', 'wall area', 'roof area','overall height','glazing area','glazing area distribution']),
     ("onehot", OneHotEncoder(sparse=False), ['orientation'])])

column.fit(X_train)
X_train_trans = column.transform(X_train)

X_test_trans = column.transform(X_test)
print('X_train_trans.shape={}, type(X_train_trans)={}'.format(X_train_trans.shape, type(X_train_trans)))
print('X_test_trans.shape={}, type(X_test_trans)={}'.format(X_test_trans.shape, type(X_test_trans)))

X_train_trans.shape=(576, 11), type(X_train_trans)=<class 'numpy.ndarray'>
X_test_trans.shape=(192, 11), type(X_test_trans)=<class 'numpy.ndarray'>

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [ ]:
!pip install mglearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mglearn in /usr/local/lib/python3.9/dist-packages (0.1.9)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from mglearn) (1.22.4)
Requirement already satisfied: joblib in /usr/local/lib/python3.9/dist-packages (from mglearn) (1.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.9/dist-packages (from mglearn) (8.4.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.9/dist-packages (from mglearn) (3.7.1)
Requirement already satisfied: cycler in /usr/local/lib/python3.9/dist-packages (from mglearn) (0.11.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (from mglearn) (1.2.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (from mglearn) (1.4.4)
Requirement already satisfied: imageio in /usr/local/lib/python3.9/dist-packages (from mglearn) (2.25.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->mglearn) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->mglearn) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/dist-packages (from matplotlib->mglearn) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->mglearn) (5.12.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->mglearn) (23.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/dist-packages (from matplotlib->mglearn) (4.39.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/dist-packages (from matplotlib->mglearn) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas->mglearn) (2022.7.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->mglearn) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->mglearn) (1.10.1)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/dist-packages (from importlib-resources>=3.2.0->matplotlib->mglearn) (3.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7->matplotlib->mglearn) (1.16.0)

## Part 4: Implement MLP using scikit-learn (5 marks)

In [ ]:
# Test using default parameters (set max_iter=500 - for this assignment, don't worry about reaching convergence)
from sklearn.neural_network import MLPRegressor

from sklearn.datasets import fetch_california_housing
california = fetch_california_housing()

mlp = MLPRegressor(max_iter=500)
mlp.fit(X_train_trans, y_train)
rs = mlp.score(X_test_trans, y_test)
print("R2 score:", rs)

R2 score: 0.9334789607540032

/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

In [ ]:
# Test using two hidden layers with 100 nodes each
mlp2 = MLPRegressor(hidden_layer_sizes=(100, 100), max_iter=500)
mlp2.fit(X_train_trans, y_train)
rs = mlp2.score(X_test_trans, y_test)
print("R2 score:", rs)

R2 score: 0.9844197102446749

/usr/local/lib/python3.9/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

In [ ]:
# Test using three hidden layers with 100 nodes each
mlp3 = MLPRegressor(hidden_layer_sizes=(100, 100, 100), max_iter=500)
mlp3.fit(X_train_trans, y_train)
rs = mlp3.score(X_test_trans, y_test)
print("R2 score:", rs)

R2 score: 0.9958270403720244

In [ ]:

!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tensorflow in /usr/local/lib/python3.9/dist-packages (2.12.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (3.8.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (23.3.3)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (2.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (1.53.0)
Requirement already satisfied: jax>=0.3.15 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (0.4.7)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (1.14.1)
Requirement already satisfied: numpy<1.24,>=1.22 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (1.22.4)
Requirement already satisfied: tensorboard<2.13,>=2.12 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (2.12.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (4.5.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (0.4.0)
Requirement already satisfied: tensorflow-estimator<2.13,>=2.12.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (2.12.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from tensorflow) (23.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (3.20.3)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (0.32.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (16.0.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from tensorflow) (67.6.1)
Requirement already satisfied: keras<2.13,>=2.12.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow) (2.12.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.9/dist-packages (from astunparse>=1.6.0->tensorflow) (0.40.0)
Requirement already satisfied: scipy>=1.7 in /usr/local/lib/python3.9/dist-packages (from jax>=0.3.15->tensorflow) (1.10.1)
Requirement already satisfied: ml-dtypes>=0.0.3 in /usr/local/lib/python3.9/dist-packages (from jax>=0.3.15->tensorflow) (0.0.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.17.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (0.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.2.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (3.4.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.13,>=2.12->tensorflow) (2.27.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.13,>=2.12->tensorflow) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.9/dist-packages (from markdown>=2.6.8->tensorboard<2.13,>=2.12->tensorflow) (6.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (1.26.15)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.21.0->tensorboard<2.13,>=2.12->tensorflow) (3.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.9/dist-packages (from werkzeug>=1.0.1->tensorboard<2.13,>=2.12->tensorflow) (2.1.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.13,>=2.12->tensorflow) (3.15.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.9/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.13,>=2.12->tensorflow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.13,>=2.12->tensorflow) (3.2.2)

## Part 5: Implement MLP using TensorFlow (7 marks)

In [ ]:
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers

Instead of scaling the data using a scikit-learn scaler, you can scale the data using a normalization layer.

In [ ]:
# Define normalization layer
normalization_layer = tf.keras.layers.experimental.preprocessing.Normalization()
normalization_layer.adapt(X_train)

Using `keras.Sequential`, implement an MLP with the same hidden layer setups as above:

In [ ]:
# One hidden layer with 100 nodes and the relu activation function
# Compile the model with loss='mean_absolute_error' and optimizer=tf.keras.optimizers.Adam(0.001)
# Fit the model using validation_split=0.2, verbose=0 and epochs=100
from tensorflow.keras.layers import Dense, Input, BatchNormalization

ten = tf.keras.models.Sequential([
    Input(shape=(X_train.shape[1],)),
    normalization_layer,
    tf.keras.layers.Dense(100, activation='relu'),
    BatchNormalization(),
    tf.keras.layers.Dense(1)
])

ten.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))

out = ten.fit(X_train, y_train, validation_split=0.2, verbose=0, epochs=100)

score = ten.evaluate(X_test, y_test)
print("loss:", score)

6/6 [==============================] - 0s 3ms/step - loss: 1.6903
loss: 1.6903247833251953

In [ ]:
# Repeat with two hidden layers with 100 nodes each and the relu activation function
from tensorflow.keras.layers import Dense, Input, BatchNormalization

ten2 = tf.keras.models.Sequential([
    Input(shape=(X_train.shape[1],)),
    normalization_layer,
    tf.keras.layers.Dense(100, activation='relu'),
    BatchNormalization(),
    tf.keras.layers.Dense(100, activation='relu'),
    BatchNormalization(),
    tf.keras.layers.Dense(1)
])

ten2.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))

out2 = ten2.fit(X_train, y_train, validation_split=0.2, epochs=100, verbose=0)

score = ten2.evaluate(X_test, y_test)
print("loss:", score)

6/6 [==============================] - 0s 3ms/step - loss: 0.7738
loss: 0.7738264203071594

In [ ]:
# Repeat with three hidden layers with 100 nodes each and the relu activation function
from tensorflow.keras.layers import Dense, Input, BatchNormalization
ten3 = tf.keras.models.Sequential([
    Input(shape=(X_train.shape[1],)),
    normalization_layer,
    tf.keras.layers.Dense(100, activation='relu'),
    BatchNormalization(),
    tf.keras.layers.Dense(100, activation='relu'),
    BatchNormalization(),
    tf.keras.layers.Dense(100, activation='relu'),
    BatchNormalization(),
    tf.keras.layers.Dense(1)
])

ten3.compile(loss='mean_absolute_error', optimizer=tf.keras.optimizers.Adam(0.001))

out3 = ten3.fit(X_train, y_train, validation_split=0.2, epochs=100, verbose=0)

score = ten3.evaluate(X_test, y_test)
print("loss:", score)

6/6 [==============================] - 0s 3ms/step - loss: 0.7330
loss: 0.7329871654510498

## Part 6: Compare the accuracy of both methods (7 marks)

For this part, calculate the mean absolute error for each model and print in a table using pandas

In [ ]:
# Calculate the MAE for the three scikit-learn tests
from sklearn.metrics import mean_absolute_error

sk1 = mlp.predict(X_test_trans)
m1 = mean_absolute_error(y_test, sk1)
print("Test1-MAE:", m1)

sk2 = mlp2.predict(X_test_trans)
m2 = mean_absolute_error(y_test, sk2)
print("Test2-MAE:", m2)

sk3 = mlp3.predict(X_test_trans)
m3 = mean_absolute_error(y_test, sk3)
print("Test3-MAE:", m3)

Test1-MAE: 1.8997446798963742
Test2-MAE: 0.9169660736377484
Test3-MAE: 0.4994860741422152

In [ ]:
# Calculate the MAE for the three tensorflow tests
tfp1 = ten.predict(X_test)
tm1 = mean_absolute_error(y_test, tfp1)
print("Test1-MAE:", tm1)

tfp2 = ten2.predict(X_test)
tm2 = mean_absolute_error(y_test, tfp2)
print("Test2-MAE:", tm2)

tfp3 = ten3.predict(X_test)
tm3 = mean_absolute_error(y_test, tfp3)
print("Test3-MAE:", tm3)

6/6 [==============================] - 0s 3ms/step
Test1-MAE: 1.690325101415316
6/6 [==============================] - 0s 2ms/step
Test2-MAE: 0.773826164205869
6/6 [==============================] - 0s 3ms/step
Test3-MAE: 0.7329867584506671

In [ ]:
# Print the results
result = {'model': ['Scikit-learn test1 (1 hidden layer)', 'Scikit-learn test2 (2 hidden layers)', 'Scikit-learn test3 (3 hidden layers)',
                  'TensorFlow test1 (1 hidden layer)', 'TensorFlow test2 (2 hidden layers)', 'TensorFlow test3 (3 hidden layers)'],

        'mae': [m1, m2, m3,
                tm1, tm2, tm3]}

table = pd.DataFrame(data=result)
table

                                  model       mae
0   Scikit-learn test1 (1 hidden layer)  1.899745
1  Scikit-learn test2 (2 hidden layers)  0.916966
2  Scikit-learn test3 (3 hidden layers)  0.499486
3     TensorFlow test1 (1 hidden layer)  1.690325
4    TensorFlow test2 (2 hidden layers)  0.773826
5    TensorFlow test3 (3 hidden layers)  0.732987

## Part 7: Questions (5 marks total)

### Question 1: Which model produced the least amount of error? (1 mark)

*ANSWER HERE*


when checked  for both Scikit-learn and tensor flow models
When we implemeneted the MLP using scikit-learn with three hidden layers with 100 nodes each and the relu activation function then we got least mean_absolute_error

### Question 2: Why are the numbers different between the scikit-learn and TensorFlow methods when we used the same number of hidden layers and hidden units per layer? (2 marks)

*ANSWER HERE*


There are a few reasons why the MAEs vary even when we use the same number of hidden layers.Different algorithms and optimization strategies are used by the scikit-learn and tensorflow libraries, accordingly.
Ex: learning rate, normalization strength, etc. can have a major impact on the performance of the model. Hyperparameter adjustment is also very important.
We must make sure that the hyperparameter values for both libraries are identical.
The MAE'S are also impacted by the preprocessing processes. For instance, if the data is scaled differently in scikit-learn and TensorFlow, this can produce different results.

### Question 3: Reflection (2 marks)
Include a sentence or two about:
- what you liked or disliked,
- found interesting, confusing, challenging, motivating
while working on this assignment.

*ANSWER HERE*


The most confusing and challenging i found is working MLP using scikit-learn and tensorflow
i was able to observe how model performance varies with the change in layers and nodes in MLP by computing and comparing the MAE for each model while altering the hidden layers and nodes. learning the hyperparameter parameters for tensorflow models felt a little tough.
I felt i needed more pratice in implementation of MLP using scikit-learn and tensor flow.